### PR TITLE
added more  information on 'get_routers_by_nickname'

### PR DESCRIPTION
**Pull request by gpunktschmitz**
currently one has to query all nodes list and parse for the nickname to get stats for the routers. ideally the output for '/nodelist' and 'get_routers_by_nickname' would be the same. for a quick fix I tried adding some information to the json for 'get_routers_by_nickname'.

### CODE REVIEW

**Comment by adrianschmutzler** [comment]
Hi, sounds reasonable to me. I will have a second thought on this and then probable merge (possibly with adjustments).

**Comment by gpunktschmitz** [comment]
maybe you could also add "router_by_mac" to return json data only for one specific router. currently not possible at all.

**Comment by adrianschmutzler** [comment]
The latter can be done with ?json
https://monitoring.freifunk-franken.de/routers/5811?json
or
https://monitoring.freifunk-franken.de/mac/f81a675a5ffb?json

**Comment by adrianschmutzler** [comment]
Ich habe das jetzt gleich ordentlich gebaut, sodass die verschiedenen Filter auf die gleiche Funktion zum erzeugen des json zugreifen:
https://github.com/FreifunkFranken/fff-monitoring/commit/dbbc607d8e44c78062ae51408c0454963a312fa7

Damit schließe ich den PR.

**Pull request closed without merging**
